// ==UserScript==
// @name Numeration for Search Engines
// @namespace se-numeration
// @description Нумерация для поисковиков: Yandex, Google, Mail.ru, Rambler, Yahoo, Bing, Sputnik. Полезен исключительно для пользователей системы продвижения сайтов - userator.ru
// @version 1.3.1
// @author Eric Draven
// @updateURL https://github.com/Eric-Draven/userscripts/raw/master/se-numeration/se-numeration.meta.js
// @downloadURL https://github.com/Eric-Draven/userscripts/raw/master/se-numeration/se-numeration.user.js
// @homepageURL https://github.com/Eric-Draven/userscripts/tree/master/se-numeration
// @include *://yandex.ru/*
// @include *://yandex.ua/*
// @include *://yandex.fr/*
// @include *://yandex.by/*
// @include *://yandex.kz/*
// @include *://yandex.com/*
// @include *://yandex.com.tr/*
// @include *://www.yandex.ru/*
// @include *://www.yandex.ua/*
// @include *://www.yandex.fr/*
// @include *://www.yandex.by/*
// @include *://www.yandex.kz/*
// @include *://www.yandex.com/*
// @include *://www.yandex.com.tr/*
// @include *://news.yandex.ru/*
// @include *://news.yandex.ua/*
// @include *://news.yandex.fr/*
// @include *://news.yandex.by/*
// @include *://news.yandex.kz/*
// @include *://news.yandex.com/*
// @include *://news.yandex.com.tr/*
// @include *://go.mail.ru/*
// @include *://rambler.ru/*
// @include *://www.rambler.ru/*
// @include *://nova.rambler.ru/*
// @include *://search.yahoo.com/*
// @include *://bing.com/*
// @include *://www.bing.com/*
// @include *://sputnik.ru/*
// @include *://www.sputnik.ru/*
// @include *://google.*
// @include *://www.google.*
// @include *://encrypted.google.*
// @match *://yandex.ru/*
// @match *://yandex.ua/*
// @match *://yandex.fr/*
// @match *://yandex.by/*
// @match *://yandex.kz/*
// @match *://yandex.com/*
// @match *://yandex.com.tr/*
// @match *://www.yandex.ru/*
// @match *://www.yandex.ua/*
// @match *://www.yandex.fr/*
// @match *://www.yandex.by/*
// @match *://www.yandex.kz/*
// @match *://www.yandex.com/*
// @match *://www.yandex.com.tr/*
// @match *://news.yandex.ru/*
// @match *://news.yandex.ua/*
// @match *://news.yandex.fr/*
// @match *://news.yandex.by/*
// @match *://news.yandex.kz/*
// @match *://news.yandex.com/*
// @match *://news.yandex.com.tr/*
// @match *://go.mail.ru/*
// @match *://rambler.ru/*
// @match *://www.rambler.ru/*
// @match *://nova.rambler.ru/*
// @match *://search.yahoo.com/*
// @match *://bing.com/*
// @match *://www.bing.com/*
// @match *://sputnik.ru/*
// @match *://www.sputnik.ru/*
// @match *://*.google.ad/*
// @match *://*.google.ae/*
// @match *://*.google.al/*
// @match *://*.google.am/*
// @match *://*.google.as/*
// @match *://*.google.at/*
// @match *://*.google.az/*
// @match *://*.google.ba/*
// @match *://*.google.be/*
// @match *://*.google.bf/*
// @match *://*.google.bg/*
// @match *://*.google.bi/*
// @match *://*.google.bj/*
// @match *://*.google.bs/*
// @match *://*.google.by/*
// @match *://*.google.ca/*
// @match *://*.google.cat/*
// @match *://*.google.cc/*
// @match *://*.google.cd/*
// @match *://*.google.cf/*
// @match *://*.google.cg/*
// @match *://*.google.ch/*
// @match *://*.google.ci/*
// @match *://*.google.cl/*
// @match *://*.google.cm/*
// @match *://*.google.co.ao/*
// @match *://*.google.co.bw/*
// @match *://*.google.co.ck/*
// @match *://*.google.co.cr/*
// @match *://*.google.co.id/*
// @match *://*.google.co.il/*
// @match *://*.google.co.in/*
// @match *://*.google.co.jp/*
// @match *://*.google.co.ke/*
// @match *://*.google.co.kr/*
// @match *://*.google.co.ls/*
// @match *://*.google.co.ma/*
// @match *://*.google.co.mz/*
// @match *://*.google.co.nz/*
// @match *://*.google.co.th/*
// @match *://*.google.co.tz/*
// @match *://*.google.co.ug/*
// @match *://*.google.co.uk/*
// @match *://*.google.co.uz/*
// @match *://*.google.co.ve/*
// @match *://*.google.co.vi/*
// @match *://*.google.co.za/*
// @match *://*.google.co.zm/*
// @match *://*.google.co.zw/*
// @match *://*.google.com.af/*
// @match *://*.google.com.ag/*
// @match *://*.google.com.ai/*
// @match *://*.google.com.ar/*
// @match *://*.google.com.au/*
// @match *://*.google.com.bd/*
// @match *://*.google.com.bh/*
// @match *://*.google.com.bn/*
// @match *://*.google.com.bo/*
// @match *://*.google.com.br/*
// @match *://*.google.com.bz/*
// @match *://*.google.com.co/*
// @match *://*.google.com.cu/*
// @match *://*.google.com.cy/*
// @match *://*.google.com.do/*
// @match *://*.google.com.ec/*
// @match *://*.google.com.eg/*
// @match *://*.google.com.et/*
// @match *://*.google.com.fj/*
// @match *://*.google.com.gh/*
// @match *://*.google.com.gi/*
// @match *://*.google.com.gt/*
// @match *://*.google.com.hk/*
// @match *://*.google.com.jm/*
// @match *://*.google.com.kh/*
// @match *://*.google.com.kh/*
// @match *://*.google.com.kw/*
// @match *://*.google.com.lb/*
// @match *://*.google.com.ly/*
// @match *://*.google.com.mm/*
// @match *://*.google.com.mt/*
// @match *://*.google.com.mx/*
// @match *://*.google.com.my/*
// @match *://*.google.com.na/*
// @match *://*.google.com.nf/*
// @match *://*.google.com.ng/*
// @match *://*.google.com.ni/*
// @match *://*.google.com.np/*
// @match *://*.google.com.om/*
// @match *://*.google.com.pa/*
// @match *://*.google.com.pe/*
// @match *://*.google.com.pg/*
// @match *://*.google.com.ph/*
// @match *://*.google.com.pk/*
// @match *://*.google.com.pr/*
// @match *://*.google.com.py/*
// @match *://*.google.com.qa/*
// @match *://*.google.com.sa/*
// @match *://*.google.com.sb/*
// @match *://*.google.com.sg/*
// @match *://*.google.com.sl/*
// @match *://*.google.com.sv/*
// @match *://*.google.com.tj/*
// @match *://*.google.com.tn/*
// @match *://*.google.com.tr/*
// @match *://*.google.com.tw/*
// @match *://*.google.com.ua/*
// @match *://*.google.com.uy/*
// @match *://*.google.com.vc/*
// @match *://*.google.com.vn/*
// @match *://*.google.cv/*
// @match *://*.google.cz/*
// @match *://*.google.de/*
// @match *://*.google.dj/*
// @match *://*.google.dk/*
// @match *://*.google.dm/*
// @match *://*.google.dz/*
// @match *://*.google.ee/*
// @match *://*.google.es/*
// @match *://*.google.fi/*
// @match *://*.google.fm/*
// @match *://*.google.fr/*
// @match *://*.google.ga/*
// @match *://*.google.ge/*
// @match *://*.google.gf/*
// @match *://*.google.gg/*
// @match *://*.google.gl/*
// @match *://*.google.gm/*
// @match *://*.google.gp/*
// @match *://*.google.gr/*
// @match *://*.google.gy/*
// @match *://*.google.hn/*
// @match *://*.google.hr/*
// @match *://*.google.ht/*
// @match *://*.google.hu/*
// @match *://*.google.ie/*
// @match *://*.google.im/*
// @match *://*.google.iq/*
// @match *://*.google.is/*
// @match *://*.google.it/*
// @match *://*.google.je/*
// @match *://*.google.jo/*
// @match *://*.google.kg/*
// @match *://*.google.ki/*
// @match *://*.google.kz/*
// @match *://*.google.la/*
// @match *://*.google.li/*
// @match *://*.google.lk/*
// @match *://*.google.lt/*
// @match *://*.google.lu/*
// @match *://*.google.lv/*
// @match *://*.google.md/*
// @match *://*.google.me/*
// @match *://*.google.mg/*
// @match *://*.google.mk/*
// @match *://*.google.ml/*
// @match *://*.google.mn/*
// @match *://*.google.ms/*
// @match *://*.google.mu/*
// @match *://*.google.mv/*
// @match *://*.google.mw/*
// @match *://*.google.ne/*
// @match *://*.google.nl/*
// @match *://*.google.no/*
// @match *://*.google.nr/*
// @match *://*.google.nu/*
// @match *://*.google.pl/*
// @match *://*.google.pn/*
// @match *://*.google.ps/*
// @match *://*.google.pt/*
// @match *://*.google.ro/*
// @match *://*.google.rs/*
// @match *://*.google.ru/*
// @match *://*.google.rw/*
// @match *://*.google.sc/*
// @match *://*.google.se/*
// @match *://*.google.sh/*
// @match *://*.google.si/*
// @match *://*.google.sk/*
// @match *://*.google.sm/*
// @match *://*.google.sn/*
// @match *://*.google.so/*
// @match *://*.google.st/*
// @match *://*.google.td/*
// @match *://*.google.tg/*
// @match *://*.google.tk/*
// @match *://*.google.tl/*
// @match *://*.google.tm/*
// @match *://*.google.to/*
// @match *://*.google.tt/*
// @match *://*.google.us/*
// @match *://*.google.vg/*
// @match *://*.google.vu/*
// @match *://*.google.ws/*
// @match *://google.com/*
// @match *://www.google.com/*
// @match *://encrypted.google.com/*
// @exclude ftp://*/*
// @grant GM_addStyle
// ==/UserScript==
